apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: react
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: amiharsh/react-test:a070a96e51
        imagePullPolicy: Always
        ports:
          - containerPort: 80
