apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: react
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: "jenkins-react.delvex.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls:
  - hosts:
      - jenkins-react.delvex.io
    secretName: jenkins-react-frontend-secret
